#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: newfeature [branch name]"
    exit 1
fi

IS_CLEAN=$(git status --short | wc -l)
if [ ${IS_CLEAN} -ne 0 ]; then
  git stash
fi

git checkout master
git pull origin master
git checkout -b $1

if [ ${IS_CLEAN} -ne 0 ]; then
  git stash pop
fi
