// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package _1_mocks

import mock "github.com/stretchr/testify/mock"

// MockReceiptDecorator is an autogenerated mock type for the ReceiptDecorator type
type MockReceiptDecorator struct {
	mock.Mock
}

// Decorate provides a mock function with given fields: receipt
func (_m *MockReceiptDecorator) Decorate(receipt *Receipt) error {
	ret := _m.Called(receipt)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Receipt) error); ok {
		r0 = rf(receipt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
