// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package _1_brief_intro

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserLoader is an autogenerated mock type for the UserLoader type
type MockUserLoader struct {
	mock.Mock
}

// LoadByID provides a mock function with given fields: ctx, userID
func (_m *MockUserLoader) LoadByID(ctx context.Context, userID string) (*User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *User
	if rf, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
