// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package _2_internal_init

import (
	"github.com/stretchr/testify/mock"
)

// MockReceiptSender is an autogenerated mock type for the ReceiptSender type
type MockReceiptSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: to, body
func (_m *MockReceiptSender) Send(to string, body string) error {
	ret := _m.Called(to, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
