// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fixed.proto

package _5_data

import (
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserFixed struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFixed) Reset()         { *m = UserFixed{} }
func (m *UserFixed) String() string { return proto.CompactTextString(m) }
func (*UserFixed) ProtoMessage()    {}
func (*UserFixed) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e628d52bdac375, []int{0}
}

func (m *UserFixed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFixed.Unmarshal(m, b)
}
func (m *UserFixed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFixed.Marshal(b, m, deterministic)
}
func (m *UserFixed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFixed.Merge(m, src)
}
func (m *UserFixed) XXX_Size() int {
	return xxx_messageInfo_UserFixed.Size(m)
}
func (m *UserFixed) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFixed.DiscardUnknown(m)
}

var xxx_messageInfo_UserFixed proto.InternalMessageInfo

func (m *UserFixed) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserFixed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserFixed) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserFixed) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserFixed) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func init() {
	proto.RegisterType((*UserFixed)(nil), "_5_data.UserFixed")
}

func init() { proto.RegisterFile("fixed.proto", fileDescriptor_25e628d52bdac375) }

var fileDescriptor_25e628d52bdac375 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcb, 0xac, 0x48,
	0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x8f, 0x37, 0x8d, 0x4f, 0x49, 0x2c, 0x49,
	0x54, 0x2a, 0xe6, 0xe2, 0x0c, 0x2d, 0x4e, 0x2d, 0x72, 0x03, 0xc9, 0x09, 0xf1, 0x71, 0x31, 0x79,
	0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x79, 0xba, 0x08, 0x09, 0x71, 0xb1, 0xf8,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac,
	0xae, 0xb9, 0x89, 0x99, 0x39, 0x12, 0xcc, 0x60, 0x41, 0x08, 0x07, 0xa4, 0xd2, 0x39, 0xb3, 0xa4,
	0x52, 0x82, 0x05, 0xa2, 0x12, 0xc4, 0x16, 0x92, 0xe0, 0x62, 0x77, 0xce, 0x2f, 0xcd, 0x2b, 0x29,
	0xaa, 0x94, 0x60, 0x05, 0x0b, 0xc3, 0xb8, 0x49, 0x6c, 0x60, 0x47, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0x7d, 0xc7, 0xe3, 0x93, 0x00, 0x00, 0x00,
}
