#!/bin/bash

set -o errexit
set -o pipefail

# Ensure we specified a directory
if [ -z "$1" ]; then
  echo "Please supply a destination directory"
  exit 1
fi

# Ensure the formatting of the source directory is consistent
DIR=${1%...}
PKG_DIR=${DIR%/}/

# Build a list of all Go file (except vendor and completely generated code)
DIRS=$(find $PKG_DIR -type f -name '*.go' -not -path "*/vendor/*" -not -path "*/z_*.go" -not -path "*/*.pb.go")

# Clean and simplify the code
gofmt -w -s -l $DIRS

# Fix imports
goimports -w -l $DIRS
